<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="CleanupAll">
    <Exec Command="dotnet jb cleanupcode &quot;$(ProjectPath)&quot; --profile=&quot;Built-in: Full Cleanup&quot;" />
  </Target>

  <Target Name="CleanupModified">
    <Exec Command="git status --porcelain=v1 &gt; &quot;$(IntermediateOutputPath)modified.txt&quot;" />

    <ReadLinesFromFile File="$(IntermediateOutputPath)modified.txt">
      <Output TaskParameter="Lines" ItemName="GitStatus" />
    </ReadLinesFromFile>

    <ItemGroup>
      <ModifiedFiles Include="@(GitStatus)">
        <File>$([System.String]::Copy('%(Identity)').Substring(3).Trim())</File>
      </ModifiedFiles>

      <CleanupFiles Include="@(ModifiedFiles->'%(File)')"
                    Condition="$([System.Text.RegularExpressions.Regex]::IsMatch('%(ModifiedFiles.File)', '\.(cs|csproj)$'))" />
    </ItemGroup>

    <PropertyGroup>
      <IncludeFiles>@(CleanupFiles,';')</IncludeFiles>
    </PropertyGroup>

    <Exec Condition="'$(IncludeFiles)' != ''"
          Command="dotnet jb cleanupcode &quot;$(SolutionPath)&quot; --profile=&quot;Built-in: Full Cleanup&quot; --include=&quot;$(IncludeFiles)&quot;" />

    <Message Condition="'$(IncludeFiles)' == ''" Importance="high" Text="No modified files to clean up." />
  </Target>
</Project>
